name: CI/CD for Spring Boot Docker App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Build your Spring Boot application (build the JAR)
      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests

      # Step 4: Build Docker image (without cache)
      - name: Build Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker:${{ github.sha }} .

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker:${{ github.sha }}

      # Step 7: Tag as 'latest' and push (optional)
      - name: Tag and push as latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-docker:latest